### ISSUE TITLE
Feature Request: Allow the mod to be added/removed gracefully

### ISSUE THREAD

**Issue by avaziri** [Ilysen/ShoppingList#2]
I am not sure exactly what part of the mod prevents it from being removed mid-playthrough. Just some ideas:

If the fact that "Shopping List" is an ability causes issues when the mod is removed, perhaps it could be reworked to not be an ability but instead something you have to key bind directly. Similar to the quick pick up features in QudUX.

If the issue is that it is difficult to make character specific settings, perhaps the string that defines the shopping list can be stored in the General Notes tab of the journal, so that the mod can be removed without issue.

If refactoring the code is too much work, perhaps there could be a menu option that would effectively disable the mod even though it is still active. Really sucks to be in a situation where it is unsafe to keep it or to remove the mod. See #1

**Comment by Ilysen** [comment]
so the main thing preventing the mod from being removable mid-playthrough is the structure of it; the list's logic is stored as a serialized `IPlayerPart` on the player object. that also stores references to the activated ability and each of the wishlists.

this alone wouldn't be too major of an issue; it would probably be fairly simple to add a button to remove the part from the player so that it could be uninstalled. what this *doesn't* account for, though, is the highlights applied to NPCs with items of interest; while I could remove the main part from the player, the potentially endless amount of highlighter parts across the game save are more or less impossible to remove cleanly. there might be ways I could work around this, but I don't know of them

ultimately at the moment, the game's API isn't really designed around being able to remove mods mid-save safely. the same sort of thing would happen if you tried to remove any kind of content mod mid-save, as well; it's just much harder to cleanly remove things from a save file than it is to add in new logic that could then modify it

as a result of all that, it'd take a pretty hefty change to the mod's internal logic to make it removable mid-save, and given the impact of it under nominal circumstances, I don't think I could really justify the time and energy expenditure on the refactoring needed to do that. what I *do* want to do is fix it to make sure that those unsafeties and problems don't happen with it, but I can't do that without more info, so at the moment neither of these issues are suuuper actionable
